name: Nazarii Bardiuk
meta_description: "Blogging about stuffs"

markdown: redcarpet
highlighter: rouge
logo: true
cover: '/assets/images/header.jpeg'
paginate: 5
baseurl: /
domain_name: 'http://nazarii.bardiuk.com'
google_analytics: 'UA-54529964-1'

# Details for the RSS feed generator
url:    'http://nazarii.bardiuk.com'
author: nbardiuk
feed:
  path: rss.xml

gems:
  - jekyll-paginate
  - jekyll-feed
