baseURL = "https://nazarii.bardiuk.com/"
languageCode = "en-us"
title = "Nazarii Bardiuk's blog"
uglyurls = true
disableKinds = ["taxonomyTerm", "section"]

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

[outputFormats.Rss]
  mediaType = "application/rss+xml"
  baseName = "feed"
  isPlainText = false

[author]
  name = "Nazarii Bardiuk"
  email = "nazarii@bardiuk.com"

[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[params]
dateform = "January 2, 2006"
