version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-{{ .Branch }}
            - stack-
      - run:
          name: Setup Slack
          command: stack setup
      - run:
          name: Build Site App
          command: stack build
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Generate Static Site
          command: stack exec site build
      - run:
          name: Publish To GitHub
          working_directory: './_site'
          command: |
            git init
            git config user.name  'CircleCI'
            git config user.email 'job@circleci.com'
            git add .
            git commit -m "publish $CIRCLE_SHA1"
            git remote add origin "$CIRCLE_REPOSITORY_URL"
            git push --force origin master
