version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve dependencies
          command: stack setup
          command: stack build --dependencies-only
      - save_cache:
          name: Cache dependencies
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Build site app
          command: stack build --pedantic
      - run:
          name: Generate static site
          command: stack exec site build
      - run:
          name: Publish GitHub pages
          working_directory: './_site'
          command: |
            # initalize repo
            git init
            git config user.name  'CircleCI'
            git config user.email 'job@circleci.com'
            # add generated files
            git add .
            git commit -m "publish $CIRCLE_SHA1 [ci skip]"
            # push to pages branch
            git remote add origin "$CIRCLE_REPOSITORY_URL"
            git push --force origin master
